In [17]:
import numpy as np

7.9 (Indexing and Slicing arrays) Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations:

In [18]:
arr = np.arange(1,16).reshape(3,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


a. Select row 2.

In [19]:
arr[2]

array([ 6,  7,  8,  9, 10])

b. Select column 5.

In [20]:
arr[:, 4]

array([ 5, 10, 15])

c. Select rows 0 and 1.

In [21]:
arr[[0,1]]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

d. Select columns 2-4.

In [26]:
arr[:, 2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

e. Select the element that is in row 1 and column 4.

In [25]:
arr[1, 4]

10

f. Select all elements from rows 1 and 2 that are in columns 0, 2 and 4

In [30]:
arr[1:3, [0,2,4]]

array([[ 6,  8, 10],
       [11, 13, 15]])